name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOCKER_BASE_TAG: ghcr.io/oscartbeaumont/cityscale

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build Docker image
        run: |
          pnpm -C web i
          export DOCKER_TAG="$DOCKER_BASE_TAG:$(git rev-parse --short HEAD)"
          ./dev.sh

      - name: Push Docker image
        run: |
          export DOCKER_TAG="$DOCKER_BASE_TAG:$(git rev-parse --short HEAD)"
          docker push "$DOCKER_TAG"

      - name: Tag and push the image as latest
        if: github.ref == 'refs/heads/main'
        run: |
          export COMMIT_DOCKER_TAG="$DOCKER_BASE_TAG:$(git rev-parse --short HEAD)"
          docker tag = "$COMMIT_DOCKER_TAG" "$DOCKER_BASE_TAG:latest"
          docker push "$DOCKER_BASE_TAG:latest"
